### ISSUE TITLE
Category of U+11046 BRAHMI VIRAMA

### ISSUE THREAD

**Issue by punchcutter** [roozbehp/unicode-data#10]
As explained in https://github.com/harfbuzz/harfbuzz/issues/1102 the USE category derived for the Brahmi Virama causes USE shaping to fail for Old Tamil Brahmi. I don't know if there's anything to do on the Unicode end, but I'm logging this here in case.

**Comment by behdad** [comment]
We should find out if @roozbehp is still interested and have time resources to continue curating this data or not. cc @PeterCon

**Comment by roozbehp** [comment]
Hi. I am closing this issue tracker and sending your feedback to Unicode. In the future, please use https://www.unicode.org/reporting.html to report issues.
