### ISSUE TITLE
Devanagari grave and acute have no SyllabicCategory

### ISSUE THREAD

**Issue by behdad** [roozbehp/unicode-data#2]
It has Position, but not Category.  Behaves like Matras.

Also, perhaps add code that checks that all characters with a position have a category?  Better yet, all assigned characters in the represented blocks have a category...

**Comment by behdad** [comment]
Same thing about (deprecated) U+0953..0954.  We handle them the same way as Bindu and Gemination_Mark and Visagra.  Or maybe we don't care about these.

**Comment by roozbehp** [comment]
Thanks for the report. I'll look and see if I can find a good category for them.

BTW, please note that there's absolutely no guarantee that something with a position will have a category, or something with certain categories will have a position. I don't think there will ever be such a guarantee in the future either.

**Comment by roozbehp** [comment]
I'll put U+17DD into Syllable_Modifier, based on the information in the Unicode chart: "indicates that the base character is the final consonant of a word with its inherent vowel sound".

**Comment by roozbehp** [comment]
U+17DD fixed by f404a9b74b83913c5cae1ef7c67fd582ac173693. Will keep open for the Devanagari grave and acute.

**Comment by roozbehp** [comment]
Hi. I am closing this issue tracker and sending your feedback to Unicode. In the future, please use https://www.unicode.org/reporting.html to report issues.
