### ISSUE TITLE
U+AA74..U+AA76 need syllabic category as Consonant or similar

### ISSUE THREAD

**Issue by behdad** [roozbehp/unicode-data#3]
The characters U+AA74..U+AA76 can take tone diacritics like U+1038, U+108A, U+109B, etc.  See https://github.com/behdad/harfbuzz/issues/218

**Comment by roozbehp** [comment]
Thanks for the report. In the future, please use http://www.unicode.org/reporting.html. There's no guarantee I'll see these in time.

In categorizing these, I think Consonant_Placeholder makes more sense, as there's some similarity to U+104E MYANMAR SYMBOL AFOREMENTIONED.

/cc @mhosken for thoughts.

**Comment by roozbehp** [comment]
BTW, here's what the original proposal, http://www.unicode.org/L2/L2008/08276-khamti-proposal.pdf says about these:

> Three logogram characters are also used which can take tone and whose meaning is according to the tone they take. They are used when transcribing speech rather than in formal writing. For example, ˀn takes three tones and means: ꩵႈ negative, ꩵႉ giving and ꩵး yes. hm also takes three different tones and means: ꩶႚ part of no (prefixed by hm negative), ꩶႊ question response marker, ꩶး there. Oay takes two tones and is used when addressing a loved one ꩴႊ or someone far away ꩴး.
