### ISSUE TITLE
Kannada, Vedic Accents, symbols

### ISSUE THREAD

**Issue by MayuraVerma** [roozbehp/unicode-data#4]
http://www.unicode.org/L2/L2001/01304-feedback.pdf
http://www.unicode.org/L2/L2003/03068-kannada.pdf
http://www.unicode.org/L2/L2003/03101-indic-dir/Kannada.pdf

In the above proposals, below seven vedic accents and symbols were proposed to UTC.
But looks like only 5 of them exist but they are in different set, they are not referenced in the Kannada unicode block notes.

Laghu and Guru are not included in the Kannada unicode block at all.

Could you please check.

1. udatta (Swarita) (vertical stroke above all characters) 
   “  ॑  “(U+0951) Devanagari - confirmed

2. Anudatta (dash below all characters)
“	॒” (U+0952) Devanagari - confirmed

3. Deergha Swarita (double vertical strokes above all characters)
   “   ᳚   “ (U+1CDA) Vedic Extension - confirmed

4. Danda and Double Danda
U+0964, U+0965  (।)	(॥)

(Still missing in the Unicode standards)

5. Guru (dash Above) 
 (U+1CD1) maybe vedic extension, Vedic tone Prenkha

(Not Confirmed)

6. Laghu (U sign above all characters)
(U+1CF5) maybe vedic extension, Vedic tone candra above

**Comment by roozbehp** [comment]
Hi. I am closing this issue tracker and sending your feedback to Unicode. In the future, please use https://www.unicode.org/reporting.html to report issues.
