### ISSUE TITLE
Khmer misc signs in Syllable_Modifier

### ISSUE THREAD

**Issue by behdad** [roozbehp/unicode-data#5]
Hi,

Currently the following Khmer misc signs are marked `Syllable_Modifier`:
```
17CB          ; Syllable_Modifier # Mn       KHMER SIGN BANTOC
17CE..17D0    ; Syllable_Modifier # Mn   [3] KHMER SIGN KAKABAT..KHMER SIGN SAMYOK SANNYA
17D3          ; Syllable_Modifier # Mn       KHMER SIGN BATHAMASAT
17DD          ; Syllable_Modifier # Mn       KHMER SIGN ATTHACAN
```
In our experience with Uniscribe and Wikipedia data, these are allowed in the middle of syllable, eg. after consonant before matra.  So, in HarfBuzz, we recategorize them as top-matras.  Would be nice to resolve this.

**Comment by roozbehp** [comment]
Please use https://www.unicode.org/reporting.html for reporting issues.

**Comment by roozbehp** [comment]
Hi. I am closing this issue tracker and sending your feedback to Unicode. In the future, please use https://www.unicode.org/reporting.html to report issues.
