### ISSUE TITLE
Category of U+0AFB GUJARATI SIGN SHADDA

### ISSUE THREAD

**Issue by dscorbett** [roozbehp/unicode-data#7]
The Indic_Syllabic_Category of U+0AFB GUJARATI SIGN SHADDA should be Gemination_Mark instead of Cantillation_Mark. First, it is a gemination mark. Second, the USE only allows Cantillation_Marks at the end of a cluster, but the second example in [section 4.2 of L2/15-103R](http://unicode.org/L2/L2015/15103r-gujarati-arabic-translit.pdf#page=3) shows that it may occur in the middle of cluster. (I know Gujarati doesn’t use the USE; I assume it should do the same thing as the USE for this character.)

**Comment by behdad** [comment]
If this also needs update in HarfBuzz, please file an issue there too, so we don't forget.

**Comment by roozbehp** [comment]
Please report issues in Unicode data files here: http://www.unicode.org/reporting.html. Issues in this issue tracker are not really seen by anybody but me.

**Comment by dscorbett** [comment]
I reported it both here and to Unicode directly.

Since HarfBuzz doesn’t support Unicode 10 yet and the Indic and USE shapers are subtly different, I am not actually sure whether this will be a problem in HarfBuzz.

**Comment by jfkthame** [comment]
It looks to me like Gemination_Mark should probably be split. Currently, there are three characters with this property in IndicSyllabicCategory.txt:

0A71          ; Gemination_Mark # Mn       GURMUKHI ADDAK
11237         ; Gemination_Mark # Mn       KHOJKI SIGN SHADDA
11A98         ; Gemination_Mark # Mn       SOYOMBO GEMINATION MARK

However, AIUI the Gurmukhi mark is different from the other two, in that it indicates gemination of the following consonant, whereas the others indicate gemination of the preceding consonant. This suggests that GURMUKHI ADDAK would _follow_ any matras etc on the preceding consonant and appear at the very end of a cluster, whereas the Khojki and Soyombo marks (and the Gujarati one that should be treated similarly) belongs immediately after the consonant it modifies, and _precedes_ vowel matras. They're functionally quite different, and fit into the syllable structure in different places.

**Comment by roozbehp** [comment]
Hi. I am closing this issue tracker and sending your feedback to Unicode. In the future, please use https://www.unicode.org/reporting.html to report issues.
