### ISSUE TITLE
Category of U+11C44 BHAIKSUKI GAP FILLER-1 and U+11C45 BHAIKSUKI GAP FILLER-2

### ISSUE THREAD

**Issue by punchcutter** [roozbehp/unicode-data#9]
As explained in https://github.com/harfbuzz/harfbuzz/issues/1035 both of these gap fillers should act like a Consonant so they can hold a visarga.

**Comment by roozbehp** [comment]
Please use https://www.unicode.org/reporting.html for reporting issues.

**Comment by roozbehp** [comment]
Hi. I am closing this issue tracker and sending your feedback to Unicode. In the future, please use https://www.unicode.org/reporting.html to report issues.
